services:
    fastfoodmanagement:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPMEYCORE_HTTP_PORT=8080
        ports:
            - "8080:8080"
            - "8081:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
