services:
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver
        ports:
            - "1499:1433"
        environment:
            - "ACCEPT_EULA=Y"
            - "MSSQL_SA_PASSWORD=bTH260704@@"

    fastfoodmanagement:
        image: myapp:latest
        container_name: fastfoodmanagement-backend
        ports:
            - "8080:8080"
        environment:
            - "ConnectionStrings__DefaultConnection=${DefaultConnection}"
        depends_on:
            - db
